<?php
/**
 * @file
 * variable.islandora_solr_primary_display_table.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'islandora_solr_primary_display_table',
  'content' => array(
    'weight' => array(
      'default' => '0',
      'grid' => '0',
      'table' => '0',
    ),
    'default' => 'default',
    'enabled' => array(
      'default' => 'default',
      'grid' => 0,
      'table' => 0,
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
